### ISSUE TITLE
Looking for Pest24 dataset

### ISSUE THREAD

**Issue by zyl1121** [yangdi-cv/TP-YOLO#2]
Hello, can you please tell me where is your Pest24 dataset come from? I've seen the Pest24 paper before, but the shared link for the dataset in that paper is no longer available. I wonder if you can share the dataset with me, or give me another source to get the Pest24 dataset.
Thank you!

**Comment by yangdi-cv** [comment]
Thank you for reaching out. We downloaded the Pest24 dataset last year; however, the link the authors originally provided in their paper is now inactive. In honour of the authors' contributions and rights, we cannot distribute the Pest24 dataset on their behalf. If you are keen on accessing the Pest24 dataset, I'd recommend contacting the authors directly using the email address provided in their publication.
