### ISSUE TITLE
Pest

### ISSUE THREAD

**Issue by 1971186279** [yangdi-cv/TP-YOLO#3]

**Comment by 1971186279** [comment]
你好，可以提供pest24的数据集吗

**Comment by yangdi-cv** [comment]
#2

**Comment by yangdi-cv** [comment]
Thank you for reaching out. We downloaded the Pest24 dataset last year; however, the link the authors originally provided in their paper is now inactive. In honour of the authors' contributions and rights, we cannot distribute the Pest24 dataset on their behalf. If you are keen on accessing the Pest24 dataset, I'd recommend contacting the authors directly using the email address provided in their publication.
